import { client } from './auth-runtime.js';
import { formatApl } from './appointment-outcomes.js';
import { RANGE_OPTIONS, rangeStart, metricRows, comparisonTrend, chartPoints, comparisonWindows } from './statistics-view.js';
const $ = (s) => document.querySelector(s); const status=$('#statsStatus'), summary=$('#statsSummary'), rows=$('#statsRows'), refresh=$('#statsRefresh'), range=$('#statsRange'), metric=$('#trendMetric'), compare=$('#trendCompare');
const TYPES=[['call','Calls started','☎'],['no-answer','No answer','○'],['virtual-appointment','Virtual appointments','▣'],['refused-appointment','Appointments refused','×'],['next','Leads moved forward','→']];
let allEvents=[], allOutcomes=[];
const title=()=>RANGE_OPTIONS.find(([id])=>id===range.value)?.[1]||'This week'; const count=(items,type)=>items.filter(x=>x.event_type===type).length;
function tile(value,label){const box=document.createElement('div'), number=document.createElement('strong'), caption=document.createElement('span');number.textContent=String(value);caption.textContent=label;box.append(number,caption);return box;}
function row(icon,label,value){const line=document.createElement('div'),left=document.createElement('span'),mark=document.createElement('i'),text=document.createElement('span'),total=document.createElement('strong');line.className='statsRow';left.className='statsLabel';mark.textContent=icon;text.textContent=label;total.textContent=String(value);left.append(mark,text);line.append(left,total);return line;}
function currentData(){const start=rangeStart(range.value), end=new Date();return {events:allEvents.filter(x=>new Date(x.created_at)>=start&&new Date(x.created_at)<=end),outcomes:allOutcomes.filter(x=>new Date(x.created_at)>=start&&new Date(x.created_at)<=end)};}
function render(){const {events,outcomes}=currentData(), m=metricRows(events,outcomes);summary.replaceChildren(tile(m.calls,'Calls started'),tile(m.results,'Call results'),tile(count(events,'next'),'Leads moved'));summary.hidden=false;rows.replaceChildren(...TYPES.map(([type,label,icon])=>row(icon,label,count(events,type))));const panel=$('#appointmentStats'),outRows=$('#appointmentStatsRows');panel.hidden=!outcomes.length;if(outcomes.length)outRows.replaceChildren(row('✓','Appointments held',m.appointments),row('○','No shows',m.noShow),row('↻','Rescheduled',m.rescheduled),row('$','APL recorded',formatApl(m.apl)),row('+','Referrals collected',m.referrals));renderTrend();}
function line(svg, points, color, dashed=false, maxValue=null){if(!points.length)return;const mapped=chartPoints(points,320,150,16,16,maxValue),item=document.createElementNS('http://www.w3.org/2000/svg','polyline');item.setAttribute('points',mapped.map(p=>`${p.x},${p.y}`).join(' '));item.setAttribute('fill','none');item.setAttribute('stroke',color);item.setAttribute('stroke-width','3');item.setAttribute('stroke-linecap','round');item.setAttribute('stroke-linejoin','round');if(dashed)item.setAttribute('stroke-dasharray','7 6');svg.append(item);for(const point of mapped){const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',point.x);dot.setAttribute('cy',point.y);dot.setAttribute('r','3');dot.setAttribute('fill',color);svg.append(dot);}}
function renderTrend(){const chosen=metric.value, label=metric.options[metric.selectedIndex].text, series=comparisonTrend(allEvents,allOutcomes,chosen,range.value,compare.value),chart=$('#trendChart'),legend=$('#trendLegend');$('#trendHeading').textContent=`${label} by day`;chart.replaceChildren();legend.replaceChildren();legend.hidden=!series.comparison.length;const maxima=Math.max(1,...series.current.map(x=>x.value),...series.comparison.map(x=>x.value));if(series.current.length){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 320 150');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');line(svg,series.current,'#247456',false,maxima);line(svg,series.comparison,'#7e8cba',true,maxima);chart.append(svg);}const addLegend=(color,text)=>{const item=document.createElement('span'),dot=document.createElement('i');dot.style.background=color;item.append(dot,document.createTextNode(text));legend.append(item);};addLegend('#247456',title());if(series.comparison.length)addLegend('#7e8cba',series.label);$('#trendCaption').textContent=series.current.length?`${title()} compared by matching day. Solid green is current; dashed blue is the comparison.`:`No ${label.toLowerCase()} recorded in this period yet.`;}
async function load(){refresh.disabled=true;status.textContent='Loading your activity…';try{const {data:sessionData,error:sessionError}=await client.auth.getSession();if(sessionError||!sessionData.session){location.replace('account.html?next=statistics.html');return;}const windows=comparisonWindows(range.value,compare.value),start=[windows.current,...windows.comparisons].reduce((earliest,w)=>!earliest||w.start<earliest?w.start:earliest,null)||rangeStart(range.value);const [{data:events,error},outcomeResponse]=await Promise.all([client.from('companion_events').select('event_type,created_at').gte('created_at',start.toISOString()).order('created_at',{ascending:true}).limit(10000),client.from('appointment_outcomes').select('status,apl,referrals,created_at').gte('created_at',start.toISOString()).order('created_at',{ascending:true}).limit(10000)]);if(error)throw error;allEvents=events||[];allOutcomes=outcomeResponse.error?[]:outcomeResponse.data||[];render();status.textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · ${title()}`;}catch(error){status.textContent=error.message||'Could not load statistics.';}finally{refresh.disabled=false;}}
refresh.addEventListener('click',load);range.addEventListener('change',load);metric.addEventListener('change',renderTrend);compare.addEventListener('change',load);load();
