const {test} = require('node:test');
const assert = require('node:assert/strict');
const {PGlite} = require('@electric-sql/pglite');
const fs = require('node:fs');
const path = require('node:path');
test('cloud SQL isolates accounts, leases a computer, rejects stale commands and consumes each action once', async () => {
  const db = new PGlite();
  const a='11111111-1111-4111-8111-111111111111', b='22222222-2222-4222-8222-222222222222', c='33333333-3333-4333-8333-333333333333';
  const device='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', command='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
  try {
    await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema public, auth to authenticated, anon; grant execute on function auth.uid() to authenticated, anon;
      insert into auth.users values ('${a}'),('${b}'),('${c}');`);
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/001_cloud_sync.sql'),'utf8'));
    await db.exec(`insert into companion_members(user_id) values ('${a}'),('${b}'); set role authenticated;`);
    const asUser = id => db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
    await asUser(a);
    await db.query('select companion_desktop($1,$2)',[device,{available:true,leadId:'123',leadName:'Fictional lead'}]);
    await assert.rejects(db.query('select companion_desktop($1)',[other]), /Another computer/);
    await asUser(b);
    assert.equal((await db.query('select * from companion_sync')).rows.length,0);
    assert.equal((await db.query("update companion_sync set lead='{}' where user_id=$1 returning user_id",[a])).rows.length,0);
    assert.equal((await db.query('select companion_take($1) as command',[device])).rows[0].command,null);
    await assert.rejects(db.query('select companion_send($1,$2,$3)',[command,device,{type:'next',leadId:'123'}]), /offline/);
    await asUser(c);
    await assert.rejects(db.query('select companion_desktop($1,$2)',[other,{leadId:'abc'}]), /row-level security/);
    await asUser(a);
    await assert.rejects(db.query('select companion_send($1,$2,$3)',[command,device,{type:'next',leadId:'wrong'}]), /lead changed/);
    for(let i=0;i<2;i++) await db.query('select companion_send($1,$2,$3)',[command,device,{type:'next',leadId:'123'}]);
    assert.equal((await db.query('select companion_take($1) as command',[device])).rows[0].command.type,'next');
    assert.equal((await db.query('select companion_take($1) as command',[device])).rows[0].command,null);
    await db.query('select companion_send($1,$2,$3)',[command,device,{type:'next',leadId:'123'}]);
    assert.equal((await db.query('select companion_take($1) as command',[device])).rows[0].command,null);
    await db.query('select companion_send($1,$2,$3)',['dddddddd-dddd-4ddd-8ddd-dddddddddddd',device,{type:'virtual-appointment',leadId:'123'}]);
    assert.equal((await db.query('select companion_take($1) as command',[device])).rows[0].command.type,'virtual-appointment');
    await db.query("update companion_sync set commands=$1",[[{type:'call',requestedAt:'2000-01-01T00:00:00Z'}]]);
    assert.equal((await db.query('select companion_take($1) as command',[device])).rows[0].command,null);
    await db.exec("update companion_sync set desktop_seen=now()-interval '1 minute'");
    await assert.rejects(db.query('select companion_send($1,$2,$3)',[other,device,{type:'next',leadId:'123'}]), /offline/);
    await db.query('select companion_desktop($1)',[other]);
    assert.equal((await db.query('select lead from companion_sync')).rows[0].lead,null);
    await db.exec('reset role');
    await db.query('update companion_members set enabled=false where user_id=$1',[a]);
    await db.exec('set role authenticated');
    assert.equal((await db.query('select * from companion_sync')).rows.length,0);
    await db.exec('reset role; set role anon');
    await assert.rejects(db.query('select * from companion_sync'), /permission denied/);
    await assert.rejects(db.query('select companion_take($1)',[device]), /permission denied/);
  } finally { await db.close(); }
});
